version: "3.8"

services:
  database:
    container_name: postgresql
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=invoice
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine  
    container_name: redis
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data 
    restart: unless-stopped 


volumes:
  db:
  redis-data:
